version: "3.9"
services:
############# PHP-FPM || PHP_7.4 ##############
  phpfpm:
    image: registry.gitlab.com/devops1502/me_images/me_php-fpm:${PHP_FPM_IMAGE_VERSION}
    restart: always
    working_dir: /app
    environment:
      XDEBUG_CONFIG: remote_enable=1 remote_host=host.docker.internal profiler_enable=0
      PHP_IDE_CONFIG: "serverName=Docker"
    extra_hosts:
      host.docker.internal: 172.17.0.1
    expose:
      - "9000"
    networks:
      app_network:
    volumes:
      - type: bind
        source: ${PROJECT_PAHT}
        target: /app
      - type: bind
        source: ${PHP_INI_CONFIG}
        target: /usr/local/etc/php/php.ini
      - type: bind
        source: ${PHP_FPM_CONFIG}
        target: /usr/local/etc/php-fpm.d/app.conf
    depends_on:
      - database
      - rabbitmq
      - redis
###############################################
################### MAIN WEB ##################
  web:
    image: nginx:${NGINX_IMAGE_VERSION}
    restart: always
    expose:
      - "80"
    ports:
      - "${NGINX_PUBLIC_PORT}:80"
    networks:
      app_network:
    volumes:
      - type: bind
        source: ${PROJECT_PAHT}
        target: /app
      - type: bind
        source: ${NGINX_MAIN_SITE_CONFIG}
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - phpfpm
###############################################
################### CDN WEB ###################
  cdn:
    image: nginx:${NGINX_IMAGE_VERSION}
    restart: always
    expose:
      - "80"
    ports:
      - "${CDN_PUBLIC_PORT}:80"
    networks:
      app_network:
    volumes:
      - type: bind
        source: ./tmp/ftp
        target: /app
        volume:
          nocopy: true
      - type: bind
        source: ${CDN_SITE_CONFIG}
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - ftp
###############################################
################### CDN WEB ###################
  cdn2:
    image: nginx:${NGINX_IMAGE_VERSION}
    restart: always
    expose:
      - "80"
    ports:
      - "${CDN_PUBLIC_PORT2}:80"
    networks:
      app_network:
    volumes:
      - type: bind
        source: ./tmp/ftp2
        target: /app
        volume:
          nocopy: true
      - type: bind
        source: ${CDN_SITE_CONFIG}
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - ftp2
###############################################
################## DataBase ###################
  database:
    image: ${MYSQL_IMAGE}:${MYSQL_IMAGE_VERSION}
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    expose:
      - "3306"
    ports:
      - "${MYSQL_PUBLIC_PORT}:3306"
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    networks:
      app_network:
###############################################
################# RMQ #########################
  rabbitmq:
    image: rabbitmq:${RMQ_IMAGE_VERSION}
    restart: always
    ports:
      - 15672:15672
      - 25672:25672
      - 5672:5672
      - 15674:15674
      - 61613:61613
    networks:
      app_network:
###############################################
################## FTP1 ########################
  ftp:
    image: fauria/vsftpd
    restart: always
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASS: ${FTP_PASS}
      PASV_MIN_PORT: ${PASV_MIN_PORT}
      PASV_MAX_PORT: ${PASV_MAX_PORT}
      LOCAL_UMASK: ${FTP_LOCAL_UMASK}
    networks:
      app_network:
    volumes:
      - ./tmp/ftp:/home/vsftpd/ftpuser
###############################################
################## FTP2 ########################
  ftp2:
    image: fauria/vsftpd
    restart: always
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASS: ${FTP_PASS}
      PASV_MIN_PORT: ${PASV2_MIN_PORT}
      PASV_MAX_PORT: ${PASV2_MAX_PORT}
      LOCAL_UMASK: ${FTP_LOCAL_UMASK}
    networks:
      app_network:
    volumes:
      - ./tmp/ftp2:/home/vsftpd/ftpuser
###############################################
########### Container for build app ###########
  db-migrations:
    image: registry.gitlab.com/devops1502/me_images/me_php-fpm:${PHP_FPM_IMAGE_VERSION}
    working_dir: /app
    command: /bin/sh /bin/build.sh
    networks:
      app_network:
    volumes:
      - type: bind
        source: ${PROJECT_PAHT}
        target: /app
      - type: bind
        source: ${PHP_INI_CONFIG}
        target: /usr/local/etc/php/php.ini
      - type: bind
        source: ./scripts/build.sh
        target: /bin/build.sh
    depends_on:
      - database
      - rabbitmq
      - redis
    profiles:
      - migration
###############################################
#################  Redis  #####################
  redis:
    image: redis:6.2.6-alpine
    restart: always
    expose:
      - "6379"
    networks:
      app_network:
###############################################
################  NODE JS  ####################
  node-watch:
    image: node:14-alpine
    tty: true
    volumes:
      - ../:/app
    working_dir: /app
    #command: sh -c "npm install && npm run watch"
###############################################
################  MAILER  ####################
  mailer:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      app_network:
###############################################
networks:
  app_network:
    # if debug not working tre uncomment this
#    ipam:
#      config:
#        - subnet: 172.17.0.0/24

